name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log directory contents before delete
      run: |
        echo "Directory contents before delete:"
        dir
      shell: pwsh

    - name: Clean previous builds
      run: |
        Remove-Item -Path "dist" -Recurse -Force
      shell: pwsh

    - name: Log directory contents after delete
      run: |
        echo "Directory contents after delete:"
        dir
      shell: pwsh

    - name: PyInstaller Action
      uses: Martin005/pyinstaller-action@v1.2.0
      with:
        python_ver: '3.12'
        spec: api/3S_PC_automation.py
        exe_path: dist/3S_PC_automation.exe
        options: --onefile, --name "3S PC automation", --noconsole,

    - name: Log directory contents after build
      run: |
        echo "Directory contents after build:"
        dir
      shell: pwsh

    - name: Commit and push executable
      run: |
        git config --global user.name "AdnaneSaber"
        git config --global user.email "adnanesaber15@gmail.com"
        git add dist/3S_PC_automation.exe
        git commit -m "Add built executable"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
